package co.edu.udea.fsi.lab03.modelo;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;

@Entity(name = "Cliente")
public class Cliente implements Serializable {

    @Column(unique = true, nullable = false)
    @Id
    private Long cedula;

    @Column(nullable = false, length = 25)
    @Basic
    private String ciudad;

    @Column(nullable = false, length = 50)
    @Basic
    private String direccion;

    @OneToMany(targetEntity = Venta.class, mappedBy = "cliente")
    private List<Venta> ventas;

    @Column(nullable = false, length = 25)
    @Basic
    private String telefono;

    @Column(nullable = false, length = 50)
    @Basic
    private String nombre;

    public Cliente() {

    }

    public Long getCedula() {
        return this.cedula;
    }

    public void setCedula(Long cedula) {
        this.cedula = cedula;
    }

    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public List<Venta> getVentas() {
        return this.ventas;
    }

    public void setVentas(List<Venta> ventas) {
        this.ventas = ventas;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 29 * hash + Objects.hashCode(this.cedula);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cliente other = (Cliente) obj;
        if (!Objects.equals(this.cedula, other.cedula)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Cliente{" + "cedula=" + cedula + ", ciudad=" + ciudad + ", direccion=" + direccion + ", telefono=" + telefono + ", nombre=" + nombre + '}';
    }
    
    
}
